/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_woshidaniu_license_admin_LicenseAdminOps */

#ifndef _Included_com_woshidaniu_license_admin_LicenseAdminOps
#define _Included_com_woshidaniu_license_admin_LicenseAdminOps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_woshidaniu_license_admin_LicenseAdminOps
 * Method:    generateLicenseFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_woshidaniu_license_admin_LicenseAdminOps_generateLicenseFile
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jint, jint, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
