/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_woshidaniu_license_LicenseOps */

#ifndef _Included_com_woshidaniu_license_LicenseOps
#define _Included_com_woshidaniu_license_LicenseOps
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_woshidaniu_license_LicenseOps
 * Method:    getDevMode
 * Signature: ()[B
 */
JNIEXPORT jstring JNICALL Java_com_woshidaniu_license_LicenseOps_getDevMode
  (JNIEnv *, jobject);

/*
 * Class:     com_woshidaniu_license_LicenseOps
 * Method:    getAuthId
 * Signature: ()[B
 */
JNIEXPORT jstring JNICALL Java_com_woshidaniu_license_LicenseOps_getAuthId
  (JNIEnv *, jobject);

/*
 * Class:     com_woshidaniu_license_LicenseOps
 * Method:    getAuthUser
 * Signature: ()[B
 */
JNIEXPORT jstring JNICALL Java_com_woshidaniu_license_LicenseOps_getAuthUser
  (JNIEnv *, jobject);

/*
 * Class:     com_woshidaniu_license_LicenseOps
 * Method:    getAuthUserCode
 * Signature: ()[B
 */
JNIEXPORT jstring JNICALL Java_com_woshidaniu_license_LicenseOps_getAuthUserCode
  (JNIEnv *, jobject);

/*
 * Class:     com_woshidaniu_license_LicenseOps
 * Method:    getStartDate
 * Signature: ()[B
 */
JNIEXPORT jstring JNICALL Java_com_woshidaniu_license_LicenseOps_getStartDate
  (JNIEnv *, jobject);

/*
 * Class:     com_woshidaniu_license_LicenseOps
 * Method:    getExpireDate
 * Signature: ()[B
 */
JNIEXPORT jstring JNICALL Java_com_woshidaniu_license_LicenseOps_getExpireDate
  (JNIEnv *, jobject);

/*
 * Class:     com_woshidaniu_license_LicenseOps
 * Method:    getAuthDate
 * Signature: ()[B
 */
JNIEXPORT jstring JNICALL Java_com_woshidaniu_license_LicenseOps_getAuthDate
  (JNIEnv *, jobject);

/*
 * Class:     com_woshidaniu_license_LicenseOps
 * Method:    getEncryptSHA
 * Signature: ()[B
 */
JNIEXPORT jstring JNICALL Java_com_woshidaniu_license_LicenseOps_getEncryptSHA
  (JNIEnv *, jobject);

/*
 * Class:     com_woshidaniu_license_LicenseOps
 * Method:    getProductName
 * Signature: ()[B
 */
JNIEXPORT jstring JNICALL Java_com_woshidaniu_license_LicenseOps_getProductName
  (JNIEnv *, jobject);

/*
 * Class:     com_woshidaniu_license_LicenseOps
 * Method:    getUsage
 * Signature: ()[B
 */
JNIEXPORT jint JNICALL Java_com_woshidaniu_license_LicenseOps_getUsage
  (JNIEnv *, jobject);

/*
 * Class:     com_woshidaniu_license_LicenseOps
 * Method:    getUsageCount
 * Signature: ()[B
 */
JNIEXPORT jint JNICALL Java_com_woshidaniu_license_LicenseOps_getUsageCount
  (JNIEnv *, jobject);

/*
 * Class:     com_woshidaniu_license_LicenseOps
 * Method:    increseUsageCount
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_woshidaniu_license_LicenseOps_increseUsageCount
  (JNIEnv *, jobject);

/*
 * Class:     com_woshidaniu_license_LicenseOps
 * Method:    checkStatus
 * Signature: ()[B
 */
JNIEXPORT jint JNICALL Java_com_woshidaniu_license_LicenseOps_checkStatus
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_woshidaniu_license_LicenseOps
 * Method:    getAvialableTime
 * Signature: ()[B
 */
JNIEXPORT jint JNICALL Java_com_woshidaniu_license_LicenseOps_getAvilableTime
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif

